f = open("data.txt", "w")
f.write("Hallo\n")
f.write("World\n")
f.close()
f = open("data.txt", "+a")
f.write("Hallo\n")
f.write("World\n")
f.close()
f = open("data.txt", "+a")
f.write("Alex\n")
f.write("Umanskky\n")
f.close()
f = open("data.txt", "+a")
f.write("Egor\n")
f.write("Umanskky\n")
f.close()